export const ARU_ACTIONS = {
  idle: {
    id: 'idle',
    expression: 'A',
    motion: 'idle-breathe',
    bubble: null,
    durationMs: 0,
    resetToIdle: false,
    priority: 0,
  },
  home: {
    id: 'home',
    expression: 'G',
    motion: 'talking-bounce',
    bubble: '¡Hola! Soy Aru, la guía virtual de Kendall ✨',
    durationMs: 2600,
    resetToIdle: true,
    priority: 3,
  },
  deepProjects: {
    id: 'deepProjects',
    expression: 'G',
    motion: 'happy-bounce',
    bubble: '¡Te cuento sus proyectos con más detalle que el portfolio!',
    durationMs: 2800,
    resetToIdle: true,
    priority: 4,
  },
  deepSkills: {
    id: 'deepSkills',
    expression: 'G',
    motion: 'selected-pop',
    bubble: 'Estas habilidades vienen de proyectos reales.',
    durationMs: 2600,
    resetToIdle: true,
    priority: 4,
  },
  deepQA: {
    id: 'deepQA',
    expression: 'G',
    motion: 'explain-focus',
    bubble: 'Kendall no solo prueba: automatiza y mejora procesos.',
    durationMs: 3200,
    resetToIdle: true,
    priority: 4,
  },
  deepAI: {
    id: 'deepAI',
    expression: 'G',
    motion: 'happy-bounce',
    bubble: 'RAG, agentes y OpenAI API son parte de su enfoque actual.',
    durationMs: 3200,
    resetToIdle: true,
    priority: 4,
  },
  deepDevops: {
    id: 'deepDevops',
    expression: 'G',
    motion: 'explain-focus',
    bubble: 'Infraestructura reproducible, CI/CD y despliegues controlados.',
    durationMs: 3000,
    resetToIdle: true,
    priority: 4,
  },
  whyHire: {
    id: 'whyHire',
    expression: 'G',
    motion: 'selected-pop',
    bubble: 'Te doy razones concretas, sin exagerar.',
    durationMs: 2800,
    resetToIdle: true,
    priority: 4,
  },
  portfolio: {
    id: 'portfolio',
    expression: 'G',
    motion: 'selected-pop',
    bubble: 'El resumen profesional completo está en AruDev 🌐',
    durationMs: 2600,
    resetToIdle: true,
    priority: 4,
  },
  thinking: {
    id: 'thinking',
    expression: 'H',
    motion: 'thinking-tilt',
    bubble: 'Mmm... déjame revisar mi base local.',
    durationMs: 2400,
    resetToIdle: true,
    priority: 4,
  },
  notFound: {
    id: 'notFound',
    expression: 'H',
    motion: 'thinking-tilt',
    bubble: 'Mmm... ese dato no lo tengo registrado todavía.',
    durationMs: 3200,
    resetToIdle: true,
    priority: 5,
  },
  angry: {
    id: 'angry',
    expression: 'I',
    motion: 'angry-shake',
    bubble: null,
    durationMs: 1600,
    resetToIdle: true,
    priority: 6,
  },
  tired: {
    id: 'tired',
    expression: 'K',
    motion: 'tired-sway',
    bubble: null,
    durationMs: 0,
    resetToIdle: false,
    priority: 2,
  },
  explainFocus: {
    id: 'explainFocus',
    expression: 'G',
    motion: 'explain-focus',
    bubble: 'Te explico el contexto detrás del resumen.',
    durationMs: 3000,
    resetToIdle: true,
    priority: 4,
  },
};

export function getAruAction(actionId, fallback = 'idle') {
  return ARU_ACTIONS[actionId] || ARU_ACTIONS[fallback] || ARU_ACTIONS.idle;
}
