export const ARU_ACTIONS = {
  idle: {
    id: 'idle',
    expression: 'A',
    motion: 'idle-breathe',
    bubble: null,
    durationMs: 0,
    resetToIdle: false,
    priority: 0,
  },
  home: {
    id: 'home',
    expression: 'G',
    motion: 'talking-bounce',
    bubble: {
      es: '¡Hola! Soy Aru, la guía virtual de Kendall ✨',
      en: 'Hi! I am Aru, Kendall’s virtual guide ✨',
    },
    sfx: 'greeting',
    durationMs: 2600,
    resetToIdle: true,
    priority: 3,
  },
  deepProjects: {
    id: 'deepProjects',
    expression: 'G',
    motion: 'happy-bounce',
    bubble: {
      es: '¡Te cuento sus proyectos con más detalle que el portfolio!',
      en: 'I’ll explain his projects in more detail than the portfolio!',
    },
    durationMs: 2800,
    resetToIdle: true,
    priority: 4,
  },
  deepSkills: {
    id: 'deepSkills',
    expression: 'G',
    motion: 'selected-pop',
    bubble: {
      es: 'Estas habilidades vienen de proyectos reales.',
      en: 'These skills come from real projects.',
    },
    durationMs: 2600,
    resetToIdle: true,
    priority: 4,
  },
  deepQA: {
    id: 'deepQA',
    expression: 'G',
    motion: 'explain-focus',
    bubble: {
      es: 'Kendall no solo prueba: automatiza y mejora procesos.',
      en: 'Kendall does not just test: he automates and improves processes.',
    },
    durationMs: 3200,
    resetToIdle: true,
    priority: 4,
  },
  deepAI: {
    id: 'deepAI',
    expression: 'G',
    motion: 'happy-bounce',
    bubble: {
      es: 'RAG, agentes y OpenAI API son parte de su enfoque actual.',
      en: 'RAG, agents, and OpenAI API are part of his current focus.',
    },
    durationMs: 3200,
    resetToIdle: true,
    priority: 4,
  },
  deepDevops: {
    id: 'deepDevops',
    expression: 'G',
    motion: 'explain-focus',
    bubble: {
      es: 'Infraestructura reproducible, CI/CD y despliegues controlados.',
      en: 'Reproducible infrastructure, CI/CD, and controlled deployments.',
    },
    durationMs: 3000,
    resetToIdle: true,
    priority: 4,
  },
  whyHire: {
    id: 'whyHire',
    expression: 'G',
    motion: 'selected-pop',
    bubble: {
      es: 'Te doy razones concretas, sin exagerar.',
      en: 'I’ll give you concrete reasons, without exaggerating.',
    },
    durationMs: 2800,
    resetToIdle: true,
    priority: 4,
  },
  portfolio: {
    id: 'portfolio',
    expression: 'G',
    motion: 'selected-pop',
    bubble: {
      es: 'El portfolio principal ahora vive en Aru ✨',
      en: 'The main portfolio now lives in Aru ✨',
    },
    durationMs: 2600,
    resetToIdle: true,
    priority: 4,
  },
  thinking: {
    id: 'thinking',
    expression: 'H',
    motion: 'thinking-tilt',
    bubble: {
      es: 'Mmm... déjame revisar mi base local.',
      en: 'Hmm... let me check my local knowledge base.',
    },
    durationMs: 2400,
    resetToIdle: true,
    priority: 4,
  },
  notFound: {
    id: 'notFound',
    expression: 'H',
    motion: 'thinking-tilt',
    bubble: {
      es: 'Mmm... ese dato no lo tengo registrado todavía.',
      en: 'Hmm... I don’t have that detail registered yet.',
    },
    sfx: 'notFound',
    durationMs: 3200,
    resetToIdle: true,
    priority: 5,
  },
  unfortunateAngry: {
    id: 'unfortunateAngry',
    expression: 'J',
    motion: 'angry-shake',
    bubble: {
      es: '¿A quién llamas desafortunada? 💢💢',
      en: 'Who are you calling unfortunate? 💢💢',
    },
    sfx: 'angry',
    durationMs: 2600,
    resetToIdle: true,
    priority: 7,
  },
  angry: {
    id: 'angry',
    expression: 'I',
    motion: 'angry-shake',
    bubble: null,
    durationMs: 1600,
    resetToIdle: true,
    priority: 6,
  },
  tired: {
    id: 'tired',
    expression: 'K',
    motion: 'tired-sway',
    bubble: null,
    durationMs: 0,
    resetToIdle: false,
    priority: 2,
  },
  explainFocus: {
    id: 'explainFocus',
    expression: 'G',
    motion: 'explain-focus',
    bubble: {
      es: 'Te explico el contexto detrás del resumen.',
      en: 'I’ll explain the context behind the summary.',
    },
    durationMs: 3000,
    resetToIdle: true,
    priority: 4,
  },
};

export function getAruAction(actionId, fallback = 'idle') {
  return ARU_ACTIONS[actionId] || ARU_ACTIONS[fallback] || ARU_ACTIONS.idle;
}
